"""initial schema

Revision ID: 0001
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column(
            "metadata_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        "ix_audit_logs_org_created", "audit_logs", ["organization_id", "created_at"], unique=False
    )
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "account_type",
            sa.Enum(
                "creator",
                "business",
                "agency",
                "personal_brand",
                "other",
                name="accounttype",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_table(
        "plans",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plans")),
        sa.UniqueConstraint("code", name=op.f("uq_plans_code")),
    )
    op.create_table(
        "users",
        sa.Column("clerk_user_id", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("full_name", sa.String(length=200), nullable=True),
        sa.Column("is_platform_admin", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("clerk_user_id", name=op.f("uq_users_clerk_user_id")),
    )
    op.create_table(
        "ai_settings",
        sa.Column("provider", sa.String(length=32), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("max_response_tokens", sa.Integer(), server_default="300", nullable=False),
        sa.Column("temperature", sa.Float(), server_default="0.4", nullable=False),
        sa.Column("confidence_threshold", sa.Float(), server_default="0.7", nullable=False),
        sa.Column(
            "comment_automation_enabled", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("dm_automation_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("comment_like_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "max_replies_per_conversation_per_hour",
            sa.Integer(),
            server_default="10",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_ai_settings_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_settings")),
        sa.UniqueConstraint("organization_id", name=op.f("uq_ai_settings_organization_id")),
    )
    op.create_index(
        op.f("ix_ai_settings_organization_id"), "ai_settings", ["organization_id"], unique=False
    )
    op.create_table(
        "automation_rules",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("priority", sa.Integer(), server_default="100", nullable=False),
        sa.Column("applies_to", sa.String(length=16), nullable=False),
        sa.Column("trigger_intents", postgresql.ARRAY(sa.String(length=40)), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "ignore",
                "like",
                "reply",
                "dm_if_permitted",
                "escalate",
                name="commentaction",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column("require_human", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("notify_owner", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "config", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_automation_rules_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_automation_rules")),
    )
    op.create_index(
        op.f("ix_automation_rules_organization_id"),
        "automation_rules",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "business_profiles",
        sa.Column("brand_name", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("industry", sa.String(length=120), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column(
            "contact_info",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "policies", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "communication_style",
            sa.Enum(
                "strict_business",
                "professional",
                "moderately_casual",
                "friendly",
                name="communicationstyle",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("custom_instructions", sa.Text(), nullable=True),
        sa.Column("timezone", sa.String(length=64), server_default="UTC", nullable=False),
        sa.Column(
            "working_hours",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "off_hours_policy", sa.String(length=24), server_default="respond", nullable=False
        ),
        sa.Column("off_hours_message", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_business_profiles_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_profiles")),
        sa.UniqueConstraint("organization_id", name=op.f("uq_business_profiles_organization_id")),
    )
    op.create_index(
        op.f("ix_business_profiles_organization_id"),
        "business_profiles",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "instagram_accounts",
        sa.Column("external_account_id", sa.String(length=64), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "token_expired",
                "disconnected",
                name="instagramaccountstatus",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("access_token_encrypted", sa.LargeBinary(), nullable=False),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "granted_permissions",
            postgresql.ARRAY(sa.String(length=100)),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("webhook_subscribed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_instagram_accounts_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instagram_accounts")),
        sa.UniqueConstraint(
            "external_account_id", name=op.f("uq_instagram_accounts_external_account_id")
        ),
    )
    op.create_index(
        op.f("ix_instagram_accounts_organization_id"),
        "instagram_accounts",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_instagram_accounts_status"), "instagram_accounts", ["status"], unique=False
    )
    op.create_table(
        "jobs",
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "done",
                "failed",
                name="processingstatus",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "run_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_jobs_organization_id_organizations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_index(op.f("ix_jobs_organization_id"), "jobs", ["organization_id"], unique=False)
    op.create_index("ix_jobs_status_run_at", "jobs", ["status", "run_at"], unique=False)
    op.create_table(
        "knowledge_documents",
        sa.Column(
            "kind",
            sa.Enum(
                "faq",
                "product",
                "service",
                "policy",
                "website",
                "custom",
                name="knowledgekind",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_knowledge_documents_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_documents")),
    )
    op.create_index(
        op.f("ix_knowledge_documents_organization_id"),
        "knowledge_documents",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "organization_members",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "owner",
                "admin",
                "manager",
                "staff",
                name="memberrole",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_organization_members_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_organization_members_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_members")),
        sa.UniqueConstraint(
            "organization_id", "user_id", name=op.f("uq_organization_members_organization_id")
        ),
    )
    op.create_index(
        op.f("ix_organization_members_organization_id"),
        "organization_members",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_members_user_id"), "organization_members", ["user_id"], unique=False
    )
    op.create_table(
        "plan_limits",
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column("metric", sa.String(length=48), nullable=False),
        sa.Column("limit_value", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["plans.id"], name=op.f("fk_plan_limits_plan_id_plans"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_limits")),
        sa.UniqueConstraint("plan_id", "metric", name=op.f("uq_plan_limits_plan_id")),
    )
    op.create_index(op.f("ix_plan_limits_plan_id"), "plan_limits", ["plan_id"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "trialing",
                "active",
                "past_due",
                "canceled",
                name="subscriptionstatus",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "interval",
            sa.Enum(
                "monthly",
                "annual",
                name="billinginterval",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("trial_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("grace_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("canceled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider_customer_id", sa.String(length=128), nullable=True),
        sa.Column("provider_subscription_id", sa.String(length=128), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_subscriptions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["plans.id"], name=op.f("fk_subscriptions_plan_id_plans")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
        sa.UniqueConstraint(
            "provider_subscription_id", name=op.f("uq_subscriptions_provider_subscription_id")
        ),
    )
    op.create_index(
        op.f("ix_subscriptions_organization_id"), "subscriptions", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_subscriptions_plan_id"), "subscriptions", ["plan_id"], unique=False)
    op.create_index(op.f("ix_subscriptions_status"), "subscriptions", ["status"], unique=False)
    op.create_table(
        "usage_limits",
        sa.Column("metric", sa.String(length=48), nullable=False),
        sa.Column("limit_value", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_usage_limits_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_limits")),
        sa.UniqueConstraint(
            "organization_id", "metric", name=op.f("uq_usage_limits_organization_id")
        ),
    )
    op.create_index(
        op.f("ix_usage_limits_organization_id"), "usage_limits", ["organization_id"], unique=False
    )
    op.create_table(
        "usage_records",
        sa.Column("metric", sa.String(length=48), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("quantity", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_usage_records_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_records")),
        sa.UniqueConstraint(
            "organization_id",
            "metric",
            "period_start",
            name=op.f("uq_usage_records_organization_id"),
        ),
    )
    op.create_index(
        op.f("ix_usage_records_organization_id"), "usage_records", ["organization_id"], unique=False
    )
    op.create_table(
        "comments",
        sa.Column("instagram_account_id", sa.UUID(), nullable=False),
        sa.Column("external_comment_id", sa.String(length=64), nullable=False),
        sa.Column("external_media_id", sa.String(length=64), nullable=False),
        sa.Column("external_parent_id", sa.String(length=64), nullable=True),
        sa.Column("author_external_id", sa.String(length=64), nullable=True),
        sa.Column("author_username", sa.String(length=64), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "intent",
            sa.Enum(
                "greeting",
                "product_query",
                "price_query",
                "service_query",
                "order_query",
                "shipping_query",
                "booking_query",
                "collaboration",
                "sponsorship",
                "affiliate",
                "complaint",
                "support",
                "general_question",
                "positive_comment",
                "negative_comment",
                "spam",
                "sexual",
                "offensive",
                "harassment",
                "uncertain",
                "human_required",
                name="intent",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column(
            "action",
            sa.Enum(
                "ignore",
                "like",
                "reply",
                "dm_if_permitted",
                "escalate",
                name="commentaction",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "done",
                "failed",
                name="processingstatus",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("reply_external_id", sa.String(length=64), nullable=True),
        sa.Column("moderation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instagram_account_id"],
            ["instagram_accounts.id"],
            name=op.f("fk_comments_instagram_account_id_instagram_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_comments_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
        sa.UniqueConstraint(
            "instagram_account_id",
            "external_comment_id",
            name=op.f("uq_comments_instagram_account_id"),
        ),
    )
    op.create_index(
        op.f("ix_comments_external_media_id"), "comments", ["external_media_id"], unique=False
    )
    op.create_index(
        op.f("ix_comments_instagram_account_id"), "comments", ["instagram_account_id"], unique=False
    )
    op.create_index(
        op.f("ix_comments_organization_id"), "comments", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_comments_status"), "comments", ["status"], unique=False)
    op.create_table(
        "customers",
        sa.Column("instagram_account_id", sa.UUID(), nullable=False),
        sa.Column("external_user_id", sa.String(length=64), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column(
            "facts", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["instagram_account_id"],
            ["instagram_accounts.id"],
            name=op.f("fk_customers_instagram_account_id_instagram_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_customers_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint(
            "instagram_account_id",
            "external_user_id",
            name=op.f("uq_customers_instagram_account_id"),
        ),
    )
    op.create_index(
        op.f("ix_customers_instagram_account_id"),
        "customers",
        ["instagram_account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customers_organization_id"), "customers", ["organization_id"], unique=False
    )
    op.create_table(
        "knowledge_entries",
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "faq",
                "product",
                "service",
                "policy",
                "website",
                "custom",
                name="knowledgekind",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(content, ''))",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["knowledge_documents.id"],
            name=op.f("fk_knowledge_entries_document_id_knowledge_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_knowledge_entries_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_entries")),
    )
    op.create_index(
        op.f("ix_knowledge_entries_document_id"), "knowledge_entries", ["document_id"], unique=False
    )
    op.create_index(op.f("ix_knowledge_entries_kind"), "knowledge_entries", ["kind"], unique=False)
    op.create_index(
        op.f("ix_knowledge_entries_organization_id"),
        "knowledge_entries",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_knowledge_entries_search",
        "knowledge_entries",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "webhook_events",
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("instagram_account_id", sa.UUID(), nullable=True),
        sa.Column("external_event_id", sa.String(length=200), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "done",
                "failed",
                name="processingstatus",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instagram_account_id"],
            ["instagram_accounts.id"],
            name=op.f("fk_webhook_events_instagram_account_id_instagram_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_webhook_events_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_events")),
        sa.UniqueConstraint("external_event_id", name=op.f("uq_webhook_events_external_event_id")),
    )
    op.create_index(
        op.f("ix_webhook_events_instagram_account_id"),
        "webhook_events",
        ["instagram_account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webhook_events_organization_id"),
        "webhook_events",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_webhook_events_status_received",
        "webhook_events",
        ["status", "received_at"],
        unique=False,
    )
    op.create_table(
        "conversations",
        sa.Column("instagram_account_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "ai_active",
                "human_required",
                "human_active",
                "resolved",
                name="conversationstate",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum(
                "low",
                "normal",
                "high",
                name="priority",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "last_intent",
            sa.Enum(
                "greeting",
                "product_query",
                "price_query",
                "service_query",
                "order_query",
                "shipping_query",
                "booking_query",
                "collaboration",
                "sponsorship",
                "affiliate",
                "complaint",
                "support",
                "general_question",
                "positive_comment",
                "negative_comment",
                "spam",
                "sexual",
                "offensive",
                "harassment",
                "uncertain",
                "human_required",
                name="intent",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column("is_lead", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "tags", postgresql.ARRAY(sa.String(length=50)), server_default="{}", nullable=False
        ),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("unread_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("assigned_user_id", sa.UUID(), nullable=True),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["assigned_user_id"],
            ["users.id"],
            name=op.f("fk_conversations_assigned_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_conversations_customer_id_customers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["instagram_account_id"],
            ["instagram_accounts.id"],
            name=op.f("fk_conversations_instagram_account_id_instagram_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_conversations_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
        sa.UniqueConstraint(
            "instagram_account_id",
            "customer_id",
            name=op.f("uq_conversations_instagram_account_id"),
        ),
    )
    op.create_index(
        op.f("ix_conversations_assigned_user_id"),
        "conversations",
        ["assigned_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversations_customer_id"), "conversations", ["customer_id"], unique=False
    )
    op.create_index(
        "ix_conversations_inbox",
        "conversations",
        ["organization_id", "state", "last_message_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversations_instagram_account_id"),
        "conversations",
        ["instagram_account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversations_organization_id"), "conversations", ["organization_id"], unique=False
    )
    op.create_table(
        "ai_usage",
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("estimated_cost", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_ai_usage_conversation_id_conversations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_ai_usage_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_usage")),
    )
    op.create_index(
        op.f("ix_ai_usage_conversation_id"), "ai_usage", ["conversation_id"], unique=False
    )
    op.create_index(
        "ix_ai_usage_org_created", "ai_usage", ["organization_id", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_ai_usage_organization_id"), "ai_usage", ["organization_id"], unique=False
    )
    op.create_table(
        "human_handoffs",
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "customer_requested",
                "complaint",
                "refund_dispute",
                "legal",
                "threat",
                "high_value_lead",
                "collaboration",
                "low_confidence",
                "missing_information",
                "repeated_dissatisfaction",
                "manual",
                name="handoffreason",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "assigned",
                "resolved",
                name="handoffstatus",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("assigned_user_id", sa.UUID(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_user_id"],
            ["users.id"],
            name=op.f("fk_human_handoffs_assigned_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_human_handoffs_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_human_handoffs_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_human_handoffs")),
    )
    op.create_index(
        op.f("ix_human_handoffs_conversation_id"),
        "human_handoffs",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_human_handoffs_organization_id"),
        "human_handoffs",
        ["organization_id"],
        unique=False,
    )
    op.create_index(op.f("ix_human_handoffs_status"), "human_handoffs", ["status"], unique=False)
    op.create_table(
        "messages",
        sa.Column("instagram_account_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("external_message_id", sa.String(length=128), nullable=True),
        sa.Column(
            "direction",
            sa.Enum(
                "inbound",
                "outbound",
                name="messagedirection",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "origin",
            sa.Enum(
                "customer",
                "ai",
                "human",
                "internal_note",
                name="messageorigin",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "received",
                "pending",
                "sent",
                "failed",
                "suppressed",
                name="deliverystatus",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "intent",
            sa.Enum(
                "greeting",
                "product_query",
                "price_query",
                "service_query",
                "order_query",
                "shipping_query",
                "booking_query",
                "collaboration",
                "sponsorship",
                "affiliate",
                "complaint",
                "support",
                "general_question",
                "positive_comment",
                "negative_comment",
                "spam",
                "sexual",
                "offensive",
                "harassment",
                "uncertain",
                "human_required",
                name="intent",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column("ai_confidence", sa.Float(), nullable=True),
        sa.Column("moderation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("author_user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_user_id"],
            ["users.id"],
            name=op.f("fk_messages_author_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["instagram_account_id"],
            ["instagram_accounts.id"],
            name=op.f("fk_messages_instagram_account_id_instagram_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_messages_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint(
            "instagram_account_id",
            "external_message_id",
            name=op.f("uq_messages_instagram_account_id"),
        ),
    )
    op.create_index(
        op.f("ix_messages_author_user_id"), "messages", ["author_user_id"], unique=False
    )
    op.create_index(
        "ix_messages_conversation_created",
        "messages",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_messages_conversation_id"), "messages", ["conversation_id"], unique=False
    )
    op.create_index(
        op.f("ix_messages_instagram_account_id"), "messages", ["instagram_account_id"], unique=False
    )
    op.create_index(
        op.f("ix_messages_organization_id"), "messages", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_messages_status"), "messages", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_status"), table_name="messages")
    op.drop_index(op.f("ix_messages_organization_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_instagram_account_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_index("ix_messages_conversation_created", table_name="messages")
    op.drop_index(op.f("ix_messages_author_user_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_human_handoffs_status"), table_name="human_handoffs")
    op.drop_index(op.f("ix_human_handoffs_organization_id"), table_name="human_handoffs")
    op.drop_index(op.f("ix_human_handoffs_conversation_id"), table_name="human_handoffs")
    op.drop_table("human_handoffs")
    op.drop_index(op.f("ix_ai_usage_organization_id"), table_name="ai_usage")
    op.drop_index("ix_ai_usage_org_created", table_name="ai_usage")
    op.drop_index(op.f("ix_ai_usage_conversation_id"), table_name="ai_usage")
    op.drop_table("ai_usage")
    op.drop_index(op.f("ix_conversations_organization_id"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_instagram_account_id"), table_name="conversations")
    op.drop_index("ix_conversations_inbox", table_name="conversations")
    op.drop_index(op.f("ix_conversations_customer_id"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_assigned_user_id"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index("ix_webhook_events_status_received", table_name="webhook_events")
    op.drop_index(op.f("ix_webhook_events_organization_id"), table_name="webhook_events")
    op.drop_index(op.f("ix_webhook_events_instagram_account_id"), table_name="webhook_events")
    op.drop_table("webhook_events")
    op.drop_index(
        "ix_knowledge_entries_search", table_name="knowledge_entries", postgresql_using="gin"
    )
    op.drop_index(op.f("ix_knowledge_entries_organization_id"), table_name="knowledge_entries")
    op.drop_index(op.f("ix_knowledge_entries_kind"), table_name="knowledge_entries")
    op.drop_index(op.f("ix_knowledge_entries_document_id"), table_name="knowledge_entries")
    op.drop_table("knowledge_entries")
    op.drop_index(op.f("ix_customers_organization_id"), table_name="customers")
    op.drop_index(op.f("ix_customers_instagram_account_id"), table_name="customers")
    op.drop_table("customers")
    op.drop_index(op.f("ix_comments_status"), table_name="comments")
    op.drop_index(op.f("ix_comments_organization_id"), table_name="comments")
    op.drop_index(op.f("ix_comments_instagram_account_id"), table_name="comments")
    op.drop_index(op.f("ix_comments_external_media_id"), table_name="comments")
    op.drop_table("comments")
    op.drop_index(op.f("ix_usage_records_organization_id"), table_name="usage_records")
    op.drop_table("usage_records")
    op.drop_index(op.f("ix_usage_limits_organization_id"), table_name="usage_limits")
    op.drop_table("usage_limits")
    op.drop_index(op.f("ix_subscriptions_status"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_plan_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_organization_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_plan_limits_plan_id"), table_name="plan_limits")
    op.drop_table("plan_limits")
    op.drop_index(op.f("ix_organization_members_user_id"), table_name="organization_members")
    op.drop_index(
        op.f("ix_organization_members_organization_id"), table_name="organization_members"
    )
    op.drop_table("organization_members")
    op.drop_index(op.f("ix_knowledge_documents_organization_id"), table_name="knowledge_documents")
    op.drop_table("knowledge_documents")
    op.drop_index("ix_jobs_status_run_at", table_name="jobs")
    op.drop_index(op.f("ix_jobs_organization_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_instagram_accounts_status"), table_name="instagram_accounts")
    op.drop_index(op.f("ix_instagram_accounts_organization_id"), table_name="instagram_accounts")
    op.drop_table("instagram_accounts")
    op.drop_index(op.f("ix_business_profiles_organization_id"), table_name="business_profiles")
    op.drop_table("business_profiles")
    op.drop_index(op.f("ix_automation_rules_organization_id"), table_name="automation_rules")
    op.drop_table("automation_rules")
    op.drop_index(op.f("ix_ai_settings_organization_id"), table_name="ai_settings")
    op.drop_table("ai_settings")
    op.drop_table("users")
    op.drop_table("plans")
    op.drop_table("organizations")
    op.drop_index("ix_audit_logs_org_created", table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
